version: '3'

services:
  app_v2:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/backend
    ports:
      - "8000:8000"
